### ISSUE TITLE
Trả lời / Góp ý

### ISSUE THREAD

**Issue by fastphat** [taminhhieu31gl/Demo-okhttp#1]
> Làm sao để khi nhiều người cùng code 1 project mà ko p tự thay đổi IP máy, dù đặt biến IP máy để gọi nhiều lần (chỉ 1 lần thay đổi) thì như thế cũng rất mất công?

Có 2 cách:
* Em deploy code BE lên 1 con server, có nhiều thằng host free lắm, em search thêm về Heroku...
* Dùng android emluator để test, static localhost ip dùng trong máy ảo là: 10.0.2.2

> Intent nên xử lý như thế nào cho ổn, dễ cho việc truyền data nhất?

Cứ dùng Parcelable hoặc persist data xuống database(sqlite - Room) rồi lấy id mà retrieve object ra

> Em chưa hiểu rõ về quy trình 1App hoạt động, tại s nhiều lúc app bị ngưng tiến trình..., e có đọc qua vòng đời của 1app android nhưng chưa có kinh nghiệm xử lý ạ?

Em đọc thêm: https://developer.android.com/guide/components/activities/activity-lifecycle. Cái này anh không giúp được, em phải tự đặt debug log rồi xem nó hoạt động thế nào. Ví dụ như khi minimize cái app rồi resume nó lại, em đặt log trong onResume, onStart, onPause, onStop xem nó ra cái gì, cái nào gọi trước cái nào gọi sau?

> Kinh nghiệm cho việc chú ý khi xoay màn hình điện thoại thì app bị ngắt... Em có hiểu là xài savedInstanceState, nhưng làm sao để ý đến việc này...

Anh chưa hiểu lắm về việc "để ý"? giờ trong fragment, e tạo một local variable dưới class, sau khi xoay màn hình mà nó không còn giữ được cái state trước đó nữa, có nghĩa nó đã bị kill và recreate lại. Trong trường hợp muốn giữ state trước đó, em phải persist đc cái previous state bằng cách dùng saveInstanceState. Thử tưởng tượng cái app gallery mà khi xoay từ portrait = lanscape mà tất cả hình biến mất? em đọc thêm ở đây: https://stackoverflow.com/questions/11182180/understanding-fragments-setretaininstanceboolean

> Cách tạo cách package như thế này em thấy ko ổn, em chưa biết cách để xây 1 kiến trúc trong android, vd như GET, POST API... e kẹt vụ xử lý luồng sao cho dễ code và đưa việc này trong class khác (như demo thì e viết trong main activity) a/c cho e vài góp ý, e cảm ơn.

Có một bài rất cụ thể ở đây: https://guides.codepath.com/android/consuming-apis-with-retrofit

Em coi thêm google samples và mấy cái project showcase để hiểu thêm về arch và best practies của tụi nó: https://github.com/android

**Comment by taminhhieu31gl** [comment]
Dạ, chào anh.
Em cảm ơn a đã giành thời gian support e ạ, chỉ mới tìm hiểu android được
thời gian ngắn nên kinh nghiệm, kiến thức chưa có nhiều, nếu không phiền em
hy vọng sẽ được nhận thêm hỗ trợ từ anh.
Em cảm ơn a ạ.

Vào CN, 5 thg 4, 2020 vào lúc 20:31 fastphat <notifications@github.com>
đã viết:
